// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/audit-logs" | "/admin/custom-requests" | "/admin/custom-requests/[id]" | "/admin/inquiries" | "/admin/inquiries/[id]" | "/admin/profile" | "/admin/projects" | "/admin/projects/[id]/edit" | "/admin/projects/import" | "/admin/projects/new" | "/admin/providers" | "/admin/providers/[id]/edit" | "/admin/providers/new" | "/admin/support" | "/admin/support/[id]" | "/admin/transactions" | "/admin/transactions/[id]" | "/become-a-partner" | "/cart" | "/custom-project" | "/forgot-password" | "/login" | "/my-inquiries" | "/my-requests" | "/my-support" | "/my-support/[id]" | "/my-support/new" | "/my-transactions" | "/partner" | "/partner-registration" | "/partner/dashboard" | "/partner/inquiries" | "/partner/inquiries/[id]" | "/partner/profile" | "/partner/register" | "/partner/solutions" | "/partner/solutions/[id]" | "/partner/solutions/[id]/edit" | "/partner/solutions/import" | "/partner/solutions/new" | "/partner/status" | "/partner/support" | "/partner/support/[id]" | "/partner/support/new" | "/partner/transactions" | "/partner/transactions/[id]" | "/partner/transactions/new" | "/privacy" | "/profile" | "/projects" | "/projects/[slug]" | "/register" | "/support" | "/terms" | "/verify-email"
type AppRouteHandlerRoutes = "/api/admin/audit-logs/export" | "/api/admin/custom-requests" | "/api/admin/custom-requests/[id]" | "/api/admin/inquiries" | "/api/admin/inquiries/[id]" | "/api/admin/projects" | "/api/admin/projects/[id]" | "/api/admin/projects/[id]/images/[imageId]" | "/api/admin/projects/[id]/images/reorder" | "/api/admin/projects/bulk" | "/api/admin/projects/import" | "/api/admin/projects/selectors" | "/api/admin/providers" | "/api/admin/providers/[id]" | "/api/admin/providers/[id]/lifecycle" | "/api/admin/providers/[id]/status" | "/api/admin/support/[id]" | "/api/admin/transactions/[id]" | "/api/admin/uploads" | "/api/auth/[...nextauth]" | "/api/auth/register" | "/api/auth/resend-otp" | "/api/auth/reset-password" | "/api/auth/signout-everywhere" | "/api/auth/verify-otp" | "/api/custom-requests" | "/api/inquiries" | "/api/partner/inquiries/[id]" | "/api/partner/profile" | "/api/partner/register" | "/api/partner/solutions" | "/api/partner/solutions/[id]" | "/api/partner/solutions/import" | "/api/partner/support" | "/api/partner/support/[id]/messages" | "/api/partner/transactions" | "/api/partner/transactions/[id]" | "/api/partner/uploads" | "/api/projects/[slug]/whatsapp" | "/api/user/password" | "/api/user/profile"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/forgot-password" | "/partner"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/audit-logs": {}
  "/admin/custom-requests": {}
  "/admin/custom-requests/[id]": { "id": string; }
  "/admin/inquiries": {}
  "/admin/inquiries/[id]": { "id": string; }
  "/admin/profile": {}
  "/admin/projects": {}
  "/admin/projects/[id]/edit": { "id": string; }
  "/admin/projects/import": {}
  "/admin/projects/new": {}
  "/admin/providers": {}
  "/admin/providers/[id]/edit": { "id": string; }
  "/admin/providers/new": {}
  "/admin/support": {}
  "/admin/support/[id]": { "id": string; }
  "/admin/transactions": {}
  "/admin/transactions/[id]": { "id": string; }
  "/api/admin/audit-logs/export": {}
  "/api/admin/custom-requests": {}
  "/api/admin/custom-requests/[id]": { "id": string; }
  "/api/admin/inquiries": {}
  "/api/admin/inquiries/[id]": { "id": string; }
  "/api/admin/projects": {}
  "/api/admin/projects/[id]": { "id": string; }
  "/api/admin/projects/[id]/images/[imageId]": { "id": string; "imageId": string; }
  "/api/admin/projects/[id]/images/reorder": { "id": string; }
  "/api/admin/projects/bulk": {}
  "/api/admin/projects/import": {}
  "/api/admin/projects/selectors": {}
  "/api/admin/providers": {}
  "/api/admin/providers/[id]": { "id": string; }
  "/api/admin/providers/[id]/lifecycle": { "id": string; }
  "/api/admin/providers/[id]/status": { "id": string; }
  "/api/admin/support/[id]": { "id": string; }
  "/api/admin/transactions/[id]": { "id": string; }
  "/api/admin/uploads": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/auth/register": {}
  "/api/auth/resend-otp": {}
  "/api/auth/reset-password": {}
  "/api/auth/signout-everywhere": {}
  "/api/auth/verify-otp": {}
  "/api/custom-requests": {}
  "/api/inquiries": {}
  "/api/partner/inquiries/[id]": { "id": string; }
  "/api/partner/profile": {}
  "/api/partner/register": {}
  "/api/partner/solutions": {}
  "/api/partner/solutions/[id]": { "id": string; }
  "/api/partner/solutions/import": {}
  "/api/partner/support": {}
  "/api/partner/support/[id]/messages": { "id": string; }
  "/api/partner/transactions": {}
  "/api/partner/transactions/[id]": { "id": string; }
  "/api/partner/uploads": {}
  "/api/projects/[slug]/whatsapp": { "slug": string; }
  "/api/user/password": {}
  "/api/user/profile": {}
  "/become-a-partner": {}
  "/cart": {}
  "/custom-project": {}
  "/forgot-password": {}
  "/login": {}
  "/my-inquiries": {}
  "/my-requests": {}
  "/my-support": {}
  "/my-support/[id]": { "id": string; }
  "/my-support/new": {}
  "/my-transactions": {}
  "/partner": {}
  "/partner-registration": {}
  "/partner/dashboard": {}
  "/partner/inquiries": {}
  "/partner/inquiries/[id]": { "id": string; }
  "/partner/profile": {}
  "/partner/register": {}
  "/partner/solutions": {}
  "/partner/solutions/[id]": { "id": string; }
  "/partner/solutions/[id]/edit": { "id": string; }
  "/partner/solutions/import": {}
  "/partner/solutions/new": {}
  "/partner/status": {}
  "/partner/support": {}
  "/partner/support/[id]": { "id": string; }
  "/partner/support/new": {}
  "/partner/transactions": {}
  "/partner/transactions/[id]": { "id": string; }
  "/partner/transactions/new": {}
  "/privacy": {}
  "/profile": {}
  "/projects": {}
  "/projects/[slug]": { "slug": string; }
  "/register": {}
  "/support": {}
  "/terms": {}
  "/verify-email": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/forgot-password": never
  "/partner": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
