// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(auth)/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../app/(auth)/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../app/(auth)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth)/verify-email/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify-email">> = Specific
  const handler = {} as typeof import("../../app/(auth)/verify-email/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(customer)/my-inquiries/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my-inquiries">> = Specific
  const handler = {} as typeof import("../../app/(customer)/my-inquiries/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(customer)/my-requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my-requests">> = Specific
  const handler = {} as typeof import("../../app/(customer)/my-requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(customer)/my-support/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my-support/[id]">> = Specific
  const handler = {} as typeof import("../../app/(customer)/my-support/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(customer)/my-support/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my-support/new">> = Specific
  const handler = {} as typeof import("../../app/(customer)/my-support/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(customer)/my-support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my-support">> = Specific
  const handler = {} as typeof import("../../app/(customer)/my-support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(customer)/my-transactions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my-transactions">> = Specific
  const handler = {} as typeof import("../../app/(customer)/my-transactions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(customer)/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../app/(customer)/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/audit-logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/audit-logs">> = Specific
  const handler = {} as typeof import("../../app/admin/audit-logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/custom-requests/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/custom-requests/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/custom-requests/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/custom-requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/custom-requests">> = Specific
  const handler = {} as typeof import("../../app/admin/custom-requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/inquiries/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/inquiries/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/inquiries/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/inquiries/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/inquiries">> = Specific
  const handler = {} as typeof import("../../app/admin/inquiries/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/profile">> = Specific
  const handler = {} as typeof import("../../app/admin/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/projects/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/projects/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/admin/projects/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/projects/import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/projects/import">> = Specific
  const handler = {} as typeof import("../../app/admin/projects/import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/projects/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/projects/new">> = Specific
  const handler = {} as typeof import("../../app/admin/projects/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/projects">> = Specific
  const handler = {} as typeof import("../../app/admin/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/providers/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/providers/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/admin/providers/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/providers/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/providers/new">> = Specific
  const handler = {} as typeof import("../../app/admin/providers/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/providers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/providers">> = Specific
  const handler = {} as typeof import("../../app/admin/providers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/support/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/support/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/support/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/support">> = Specific
  const handler = {} as typeof import("../../app/admin/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/transactions/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/transactions/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/transactions/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/transactions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/transactions">> = Specific
  const handler = {} as typeof import("../../app/admin/transactions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/become-a-partner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/become-a-partner">> = Specific
  const handler = {} as typeof import("../../app/become-a-partner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cart">> = Specific
  const handler = {} as typeof import("../../app/cart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/custom-project/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/custom-project">> = Specific
  const handler = {} as typeof import("../../app/custom-project/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partner-registration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner-registration">> = Specific
  const handler = {} as typeof import("../../app/partner-registration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partner/(portal)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner/dashboard">> = Specific
  const handler = {} as typeof import("../../app/partner/(portal)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partner/(portal)/inquiries/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner/inquiries/[id]">> = Specific
  const handler = {} as typeof import("../../app/partner/(portal)/inquiries/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partner/(portal)/inquiries/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner/inquiries">> = Specific
  const handler = {} as typeof import("../../app/partner/(portal)/inquiries/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partner/(portal)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner">> = Specific
  const handler = {} as typeof import("../../app/partner/(portal)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partner/(portal)/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner/profile">> = Specific
  const handler = {} as typeof import("../../app/partner/(portal)/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partner/(portal)/solutions/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner/solutions/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/partner/(portal)/solutions/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partner/(portal)/solutions/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner/solutions/[id]">> = Specific
  const handler = {} as typeof import("../../app/partner/(portal)/solutions/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partner/(portal)/solutions/import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner/solutions/import">> = Specific
  const handler = {} as typeof import("../../app/partner/(portal)/solutions/import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partner/(portal)/solutions/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner/solutions/new">> = Specific
  const handler = {} as typeof import("../../app/partner/(portal)/solutions/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partner/(portal)/solutions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner/solutions">> = Specific
  const handler = {} as typeof import("../../app/partner/(portal)/solutions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partner/(portal)/support/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner/support/[id]">> = Specific
  const handler = {} as typeof import("../../app/partner/(portal)/support/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partner/(portal)/support/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner/support/new">> = Specific
  const handler = {} as typeof import("../../app/partner/(portal)/support/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partner/(portal)/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner/support">> = Specific
  const handler = {} as typeof import("../../app/partner/(portal)/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partner/(portal)/transactions/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner/transactions/[id]">> = Specific
  const handler = {} as typeof import("../../app/partner/(portal)/transactions/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partner/(portal)/transactions/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner/transactions/new">> = Specific
  const handler = {} as typeof import("../../app/partner/(portal)/transactions/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partner/(portal)/transactions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner/transactions">> = Specific
  const handler = {} as typeof import("../../app/partner/(portal)/transactions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partner/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner/register">> = Specific
  const handler = {} as typeof import("../../app/partner/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partner/status/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner/status">> = Specific
  const handler = {} as typeof import("../../app/partner/status/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[slug]">> = Specific
  const handler = {} as typeof import("../../app/projects/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects">> = Specific
  const handler = {} as typeof import("../../app/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support">> = Specific
  const handler = {} as typeof import("../../app/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/audit-logs/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/audit-logs/export">> = Specific
  const handler = {} as typeof import("../../app/api/admin/audit-logs/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/custom-requests/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/custom-requests/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/custom-requests/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/custom-requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/custom-requests">> = Specific
  const handler = {} as typeof import("../../app/api/admin/custom-requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/inquiries/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/inquiries/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/inquiries/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/inquiries/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/inquiries">> = Specific
  const handler = {} as typeof import("../../app/api/admin/inquiries/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/projects/[id]/images/[imageId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/projects/[id]/images/[imageId]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/projects/[id]/images/[imageId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/projects/[id]/images/reorder/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/projects/[id]/images/reorder">> = Specific
  const handler = {} as typeof import("../../app/api/admin/projects/[id]/images/reorder/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/projects/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/projects/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/projects/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/projects/bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/projects/bulk">> = Specific
  const handler = {} as typeof import("../../app/api/admin/projects/bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/projects/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/projects/import">> = Specific
  const handler = {} as typeof import("../../app/api/admin/projects/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/projects">> = Specific
  const handler = {} as typeof import("../../app/api/admin/projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/projects/selectors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/projects/selectors">> = Specific
  const handler = {} as typeof import("../../app/api/admin/projects/selectors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/providers/[id]/lifecycle/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/providers/[id]/lifecycle">> = Specific
  const handler = {} as typeof import("../../app/api/admin/providers/[id]/lifecycle/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/providers/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/providers/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/providers/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/providers/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/providers/[id]/status">> = Specific
  const handler = {} as typeof import("../../app/api/admin/providers/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/providers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/providers">> = Specific
  const handler = {} as typeof import("../../app/api/admin/providers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/support/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/support/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/support/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/transactions/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/transactions/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/transactions/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/uploads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/uploads">> = Specific
  const handler = {} as typeof import("../../app/api/admin/uploads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/resend-otp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/resend-otp">> = Specific
  const handler = {} as typeof import("../../app/api/auth/resend-otp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../app/api/auth/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/signout-everywhere/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signout-everywhere">> = Specific
  const handler = {} as typeof import("../../app/api/auth/signout-everywhere/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/verify-otp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/verify-otp">> = Specific
  const handler = {} as typeof import("../../app/api/auth/verify-otp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/custom-requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/custom-requests">> = Specific
  const handler = {} as typeof import("../../app/api/custom-requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/inquiries/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inquiries">> = Specific
  const handler = {} as typeof import("../../app/api/inquiries/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/partner/inquiries/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/partner/inquiries/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/partner/inquiries/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/partner/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/partner/profile">> = Specific
  const handler = {} as typeof import("../../app/api/partner/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/partner/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/partner/register">> = Specific
  const handler = {} as typeof import("../../app/api/partner/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/partner/solutions/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/partner/solutions/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/partner/solutions/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/partner/solutions/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/partner/solutions/import">> = Specific
  const handler = {} as typeof import("../../app/api/partner/solutions/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/partner/solutions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/partner/solutions">> = Specific
  const handler = {} as typeof import("../../app/api/partner/solutions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/partner/support/[id]/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/partner/support/[id]/messages">> = Specific
  const handler = {} as typeof import("../../app/api/partner/support/[id]/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/partner/support/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/partner/support">> = Specific
  const handler = {} as typeof import("../../app/api/partner/support/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/partner/transactions/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/partner/transactions/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/partner/transactions/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/partner/transactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/partner/transactions">> = Specific
  const handler = {} as typeof import("../../app/api/partner/transactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/partner/uploads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/partner/uploads">> = Specific
  const handler = {} as typeof import("../../app/api/partner/uploads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[slug]/whatsapp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[slug]/whatsapp">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[slug]/whatsapp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/user/password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/password">> = Specific
  const handler = {} as typeof import("../../app/api/user/password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/user/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/profile">> = Specific
  const handler = {} as typeof import("../../app/api/user/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(auth)/forgot-password/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../app/(auth)/forgot-password/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(customer)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(customer)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partner/(portal)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/partner">> = Specific
  const handler = {} as typeof import("../../app/partner/(portal)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
